import { Component, ChangeDetectionStrategy, input } from '@angular/core';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import {
  heroSun,
  heroMoon,
  heroComputerDesktop,
  heroBars3,
  heroXMark,
  heroHome,
  heroChartBarSquare,
  heroArrowRightOnRectangle,
  heroUsers,
  heroPlus,
  heroMagnifyingGlass,
  heroPencilSquare,
  heroChevronLeft,
  heroChevronRight,
  heroArrowLeft,
  heroTrash,
  heroExclamationTriangle,
  heroDocumentText,
  heroCurrencyDollar,
  heroPaperClip,
  heroTruck,
  heroArrowUpTray,
  heroFolderOpen,
  heroInformationCircle,
  heroMapPin,
  heroMap,
  heroBanknotes,
  heroClipboardDocumentCheck,
  heroArrowPath,
  heroCog6Tooth,
  heroUserCircle,
  heroChevronDown,
  heroChatBubbleLeftRight,
  heroSparkles,
  heroPaperAirplane,
  heroInboxStack,
} from '@ng-icons/heroicons/outline';

@Component({
  selector: 'ui-icon',
  standalone: true,
  imports: [NgIconComponent],
  providers: [
    provideIcons({
      heroSun,
      heroMoon,
      heroComputerDesktop,
      heroBars3,
      heroXMark,
      heroHome,
      heroChartBarSquare,
      heroArrowRightOnRectangle,
      heroUsers,
      heroPlus,
      heroMagnifyingGlass,
      heroPencilSquare,
      heroChevronLeft,
      heroChevronRight,
      heroArrowLeft,
      heroTrash,
      heroExclamationTriangle,
      heroDocumentText,
      heroCurrencyDollar,
      heroPaperClip,
      heroTruck,
      heroArrowUpTray,
      heroFolderOpen,
      heroInformationCircle,
      heroMapPin,
      heroMap,
      heroBanknotes,
      heroClipboardDocumentCheck,
      heroArrowPath,
      heroCog6Tooth,
      heroUserCircle,
      heroChevronDown,
      heroChatBubbleLeftRight,
      heroSparkles,
      heroPaperAirplane,
      heroInboxStack,
    }),
  ],
  templateUrl: './icon.component.html',
  styleUrl: './icon.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UiIconComponent {
  name = input.required<string>();
  size = input<string>('1.25rem');
}
